---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/orders/{order_id}/order_items":
    get:
      summary: List all order items
      tags:
      - Order Items
      responses:
        '200':
          description: ok
    post:
      summary: Create an order item
      tags:
      - Order Items
      parameters: []
      responses:
        '201':
          description: Order item created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: integer
                quantity:
                  type: integer
                unit_price:
                  type: number
              required:
              - product_id
              - quantity
              - unit_price
  "/api/v1/order_items/{id}":
    parameters:
    - name: id
      in: path
      description: Order Item ID
      required: true
      schema:
        type: string
    get:
      summary: Show an order item
      tags:
      - Order Items
      responses:
        '200':
          description: ok
        '404':
          description: Order item not found
    patch:
      summary: Update an order item
      tags:
      - Order Items
      parameters: []
      responses:
        '200':
          description: Order item updated
        '404':
          description: Order item not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: integer
                quantity:
                  type: integer
                unit_price:
                  type: number
              required:
              - product_id
              - quantity
              - unit_price
    delete:
      summary: Delete an order item
      tags:
      - Order Items
      responses:
        '200':
          description: Order item deleted
        '404':
          description: Order item not found
  "/api/v1/orders":
    get:
      summary: List all orders
      tags:
      - Orders
      responses:
        '200':
          description: ok
    post:
      summary: Create an order
      tags:
      - Orders
      parameters: []
      responses:
        '201':
          description: Order created
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  nullable: true
                order_items_attributes:
                  type: array
                  items:
                    type: object
                    properties:
                      product_id:
                        type: integer
                      quantity:
                        type: integer
                    required:
                    - product_id
                    - quantity
              required:
              - order_items_attributes
  "/api/v1/orders/{id}":
    parameters:
    - name: id
      in: path
      description: Order ID
      required: true
      schema:
        type: string
    get:
      summary: Show an order
      tags:
      - Orders
      responses:
        '200':
          description: ok
        '404':
          description: Order not found
    patch:
      summary: Update an order
      tags:
      - Orders
      parameters: []
      responses:
        '200':
          description: Order updated
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
              required:
              - status
    delete:
      summary: Delete an order
      tags:
      - Orders
      responses:
        '204':
          description: Order deleted
        '404':
          description: Order not found
  "/api/v1/products":
    get:
      summary: List all products
      tags:
      - Products
      responses:
        '200':
          description: ok
    post:
      summary: Create a product
      tags:
      - Products
      parameters: []
      responses:
        '201':
          description: Product created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                description:
                  type: string
              required:
              - name
              - price
              - description
  "/api/v1/products/{id}":
    parameters:
    - name: id
      in: path
      description: Product ID
      required: true
      schema:
        type: string
    get:
      summary: Show a product
      tags:
      - Products
      responses:
        '200':
          description: ok
        '404':
          description: Product not found
    patch:
      summary: Update a product
      tags:
      - Products
      parameters: []
      responses:
        '200':
          description: Product updated
        '404':
          description: Product not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                description:
                  type: string
              required:
              - name
              - price
              - description
    delete:
      summary: Delete a product
      tags:
      - Products
      responses:
        '200':
          description: Product deleted
        '404':
          description: Product not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
