---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/orders":
    get:
      summary: List all orders
      tags:
      - Orders
      responses:
        '200':
          description: ok
    post:
      summary: Create an order
      tags:
      - Orders
      parameters: []
      responses:
        '201':
          description: Order created
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                order_items_attributes:
                  type: array
                  items:
                    type: object
                    properties:
                      product_id:
                        type: integer
                      quantity:
                        type: integer
                      unit_price:
                        type: integer
                    required:
                    - product_id
                    - quantity
              required:
              - order_items_attributes
  "/api/v1/orders/{id}":
    parameters:
    - name: id
      in: path
      description: Order ID
      required: true
      schema:
        type: string
    get:
      summary: Show an order by ID
      tags:
      - Orders
      responses:
        '200':
          description: ok
        '404':
          description: Order not found
    patch:
      summary: Update an order
      tags:
      - Orders
      parameters: []
      responses:
        '200':
          description: Order updated
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
              required:
              - status
    delete:
      summary: Delete an order
      tags:
      - Orders
      responses:
        '204':
          description: Order deleted
        '404':
          description: Order not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
