name: Build, Lint & Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_lint_test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.8
          bundler-cache: true

      - name: Install dependencies
        working-directory: ./backend
        run: |
          bundle install

      - name: Run Rubocop
        working-directory: ./backend
        run: |
          bundle exec rubocop

      - name: Setup and run tests
        working-directory: ./backend
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/app_test
        run: |
          bundle exec rails db:create db:schema:load db:test:prepare
          bundle exec rails test
